# **Laboratorio 03**

In [1]:
import pandas as pd

# Cargar datos
df = pd.read_csv('https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

**Parte 1: Limpieza y preparación**

In [2]:
#Número de filas y columnas.

df.shape

(8807, 12)

In [3]:
#Tipos de datos.

df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [4]:
#Valores nulos por columna.

df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
#Convertir date_added a tipo fecha

df["date_added"] = df["date_added"].str.strip()
df["date_added"] = pd.to_datetime(df["date_added"])

In [7]:
#Crear columnas con assign

df = df.assign(
    year_added=df["date_added"].dt.year,
    month_added=df["date_added"].dt.month
)

**Parte 2: Técnicas Avanzadas de pandas**

In [8]:
#.loc

df_movies_2018 = df.loc[
    (df["type"] == "Movie") & (df["year_added"] > 2018)
]

In [9]:
#str.contains() --> Títulos con "love"

df_love = df.loc[
    df["title"].str.contains("love", case=False, na=False)
]

#str.extract() --> duración (min)

df["duration_minutes"] = df["duration"].str.extract(r"(\d+)").astype(float)

In [10]:
#explode()

df_exploded = df.explode("listed_in")

In [11]:
#Top 10 géneros más frecuentes

top_genres = df_exploded["listed_in"].value_counts().head(10)

In [13]:
#where() y mask()

df["is_long_where"] = df["duration_minutes"].where(
    df["duration_minutes"] > 120,
    other="No largo"
)

df["is_long_mask"] = df["duration_minutes"].mask(
    df["duration_minutes"] <= 120,
    other="No largo"
)

In [14]:
#.loc

df_filtered = df.loc[
    (df["duration_minutes"] > 100) &
    (df["rating"] == "R") &
    (df["country"] == "United States")
]

In [15]:
#Top 10 películas más largas

**Pregunta Desafío**

In [18]:
df_genre_rating = df.explode("listed_in")

df_genre_rating[["listed_in", "rating"]].value_counts().head(10)

listed_in                                         rating
Stand-Up Comedy                                   TV-MA     284
Dramas, International Movies                      TV-MA     154
Dramas, Independent Movies, International Movies  TV-MA     142
Dramas, International Movies                      TV-14     139
Comedies, Dramas, International Movies            TV-14     139
Kids' TV                                          TV-Y      117
Documentaries                                     TV-MA     115
Children & Family Movies, Comedies                PG         99
Documentaries                                     TV-14      98
Dramas, International Movies, Romantic Movies     TV-14      92
Name: count, dtype: int64

**¿Cuáles son las combinaciones más frecuentes de género y rating en el dataset?**


Los resultados muestran que las combinaciones más frecuentes entre género y rating se concentran principalmente en contenido de tipo “Stand-Up Comedy” con clasificación “TV-MA”, siendo la combinación más repetida del dataset (284 apariciones).

En segundo lugar, destacan combinaciones de dramas e internacional movies, especialmente con ratings TV-MA y TV-14, lo que indica una fuerte presencia de contenido adulto o para audiencias mayores en producciones internacionales.

También aparecen con frecuencia combinaciones mixtas como:

Dramas + Independent + International Movies (TV-MA)
Comedias + Dramas + Internacionales (TV-14)

Esto sugiere que el catálogo de Netflix no está dominado por géneros “puros”, sino por contenidos híbridos, donde los dramas y las producciones internacionales tienen un rol central.

En categorías familiares o infantiles, aparecen combinaciones como:

Kids’ TV (TV-Y)
Children & Family Movies (PG)

pero con menor frecuencia en comparación con contenido adulto.

**¿Existen películas con el mismo nombre (tittle) pero con distinto año de lanzamiento (release_year)?**

No, no existen películas con el mismo nombre (title) que presenten distintos años de lanzamiento (release_year) en el dataset. Esto indica que, aunque puedan existir títulos repetidos, estos corresponden al mismo año de lanzamiento y no a versiones diferentes del contenido en años distintos.

In [23]:
df.loc[
    df.duplicated(subset=["title"], keep=False),
    ["title", "release_year"]
].duplicated(subset=["title", "release_year"]).any()

np.False_

**¿Cuántos títulos únicos hay en total en la columna title?**

En el dataset existen 8807 títulos únicos en la columna title. Esto indica que cada registro corresponde a un contenido distinto, sin repeticiones de nombres en la base de datos.

In [24]:
df["title"].nunique()

8807